# Dockerfile.api

FROM python:3.10-slim

# Répertoire de travail
WORKDIR /app

# Copier les dépendances
COPY api/requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code API
COPY api/ .

# Copier les modèles
COPY models/ /app/../models/

# Exposer le port
EXPOSE 8000

# Lancer l'API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]